### ISSUE TITLE
[Crash report] when you click on the same color

### ISSUE THREAD

**Issue by tiprata** [ulrobin/dynamicColorPage#1]
Hi ! I tried your plug-in, just wanted to let you know that when you click on the icon of the color who is presently used , it made my Google Chrome crash every time. I don't know where it's from, and i think the simpliest way to fix it would be to make the color already in use "unclickable".
Nice job btw !

**Comment by ulrobin** [comment]
I've solved the problem :+1: 

Thanks for reporting the crash :)
