### ISSUE TITLE
Site web Error 404

### ISSUE THREAD

**Issue by Imvi10** [ulrobin/dynamicColorPage#2]
When i click on downoad in  your site the link "http://https//github.com/ulrobin/dynamicColorPage" is broken , the script its super thanks

**Comment by Imvi10** [comment]
and could you add an example

**Comment by ulrobin** [comment]
Link works again, now :+1:

Thanks for reporting that :)

**Comment by ulrobin** [comment]
@Imvi10

An example page is dynamic-color-page.hol.es :)

The typography examples show exactly what the script does :)
